### ISSUE TITLE
Syntax error in database rules

### ISSUE THREAD

**Issue by socketlab** [jgudo/ecommerce-react#11]
I'm trying to deploy, using firebase hosting and the following error happens:

Error: Syntax error in database rules:
61:25: No such method/property 'isArray'.

in:

"imageCollection": {
".validate": "newData.isArray()"
}

Would you help me?

**Comment by jgudo** [comment]
I mindlessly set isArray method which in fact doesn't really exist. You can just remove the validation for now.
