### ISSUE TITLE
getting error while installing npm  some 

### ISSUE THREAD

**Issue by aslamsk** [jgudo/ecommerce-react#18]
getting error while installing npm  some 
![Screenshot (30)](https://user-images.githubusercontent.com/54580538/97087036-f35e5980-15db-11eb-940e-686e1f82f91f.png)

**Comment by jgudo** [comment]
Have you tried deleting the package-lock.json and node_modules then run npm install again?

**Comment by aslamsk** [comment]
Yah I tried  but till getting

**Comment by jgudo** [comment]
Even after cleaning the npm cache? ```npm cache clean --force```

**Comment by aslamsk** [comment]
This process also done but not worked till getting same to same error

**Comment by jgudo** [comment]
What version of npm are you using? 
Try again deleting node_modules + package-lock.json + running ```npm cache clean --force```. If the problem still exists, try reinstalling/update node/npm. I'm going to close this since I can't reproduce the problem and it seems that problem is in your end.
