### ISSUE TITLE
I am not able to retrieve products

### ISSUE THREAD

**Issue by 6samuel** [jgudo/ecommerce-react#2]
I created a database for products but not able to get them. Can you please share the screenshot of your database
this is the error i am getting
![SharedScreenshot](https://user-images.githubusercontent.com/19704340/74087622-36ab8300-4ab4-11ea-93ac-9dc950846cd9.jpg)

**Comment by jgudo** [comment]
Looks like you're passing undefined data in selectFilter(). Have you added the products in the database using the admin user? You must uncomment all the admin-related stuffs inside src/routers/AppRouter.js and lastly, inside src/reducers/authReducer.js, just change the type property of initState from 'client' into 'admin' to use the admin mode. Then only you can perform CRUD operations.

**Comment by 6samuel** [comment]
> Looks like you're passing undefined data in selectFilter(). Have you added the products in the database using the admin user? You must uncomment all the admin-related stuffs inside src/routers/AppRouter.js and lastly, inside src/reducers/authReducer.js, just change the type property of initState from 'client' into 'admin' to use the admin mode. Then only you can perform CRUD operations.

I did as you asked but how to login to admin pannel.

**Comment by 6samuel** [comment]
> Looks like you're passing undefined data in selectFilter(). Have you added the products in the database using the admin user? You must uncomment all the admin-related stuffs inside src/routers/AppRouter.js and lastly, inside src/reducers/authReducer.js, just change the type property of initState from 'client' into 'admin' to use the admin mode. Then only you can perform CRUD operations.

I tried to login using the available signin method but it is not redirecting to admin dashboard. Am i missing anything.

**Comment by jgudo** [comment]
The default user auth could've been persisting. Log out the default user or you can delete the auth details of user in localStorage. Then you must be able to get to the /dashboard page

**Comment by jgudo** [comment]
The admin doesn't have the available login methods unlike the client does. That's the problem that I have with the admin authentication.

**Comment by 6samuel** [comment]
> The default user auth could've been persisting. Log out the default user or you can delete the auth details of user in localStorage. Then you must be able to get to the /dashboard page

I did everything man still the dashboard is not opening. Is there any other things i need to keep in mind. 
see i have a work around for this error but i need to get to the admin dashboard to fix it.

**Comment by jgudo** [comment]
Are getting any error or it just won't redirect you to the admin?

**Comment by jgudo** [comment]
Have done all this? 

1. Uncomment all admin-stuffs inside src/routers/AppRouter.js
2. Inside src/reducer/authReducer.js,  if you don't want a test user, delete or comment out the initState variable and set the state to an empty object {} If you want to use admin, you must change type property to 'admin' to use admin mode.
3. Delete the auth data in localStorage if it exists (i think the key name is 'root')

**Comment by 6samuel** [comment]
> Are you getting any error or it just don't redirect you to the admin?

After Clearing the localstorage i am being redirected to dashboard but for few second only. then again it is going back to the homepage

**Comment by 6samuel** [comment]
I Figured it out by myself there was a small error. I had to initialize the admin type separately. the initState did not work for the admin type. 

I Recommend we should use firebase rules with custom claims. that way you don't have to worry about the dashboard section. any way thanks

**Comment by jgudo** [comment]
Great! It would be awesome if you could make a pull request for these necessary changes. 👌
