### ISSUE TITLE
How to deploy the project using firebase

### ISSUE THREAD

**Issue by sourabhz-7** [jgudo/ecommerce-react#20]
How to deploy the project using firebase

**Comment by jgudo** [comment]
Go to console on your firebase project, and click on Hosting on the left menu then click on get started. The rest will follow.
![screenshot-console](https://user-images.githubusercontent.com/30772059/97438942-7f67dc80-1960-11eb-9f07-9a90f0211e27.PNG) 

For more info about firebase hosting [Firebase Hosting](https://firebase.google.com/docs/hosting/quickstart)

**Comment by jgudo** [comment]
After successfully deploying the  project, just add the secret keys for the configuration of your firebase project for continuous deployment. Github will trigger the deployment itself when the repo has been modified. 

Add the following  secret keys for your repo.  [How to add secret keys on github](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#:~:text=Creating%20encrypted%20secrets%20for%20a%20repository,-To%20create%20secrets&text=To%20create%20secrets%20for%20an,the%20left%20sidebar%2C%20click%20Secrets.)

FIREBASE_API_KEY
FIREBASE_AUTH_DOMAIN
FIREBASE_DB_URL
FIREBASE_PROJECT_ID
FIREBASE_STORAGE_BUCKET
FIREBASE_MSG_SENDER_ID
FIREBASE_APP_ID

**Comment by sourabhz-7** [comment]
Thank you so much

**Comment by sourabhz-7** [comment]
Sir how can we add a color select and size select option in our products
details card
