### ISSUE TITLE
Adding color select and size select option in products card

### ISSUE THREAD

**Issue by sourabhz-7** [jgudo/ecommerce-react#21]
Sir if a person wants to order the product (eg. The glasses) but of different color so how to add color select option in the product Modal section so that he can choose the colour varient and then add to the basket the specific varient of that product.
Will be thankful if you help.

**Comment by jgudo** [comment]
@sourabhz-7  You need to add a new field to every single document on your firestore collection. 
To my knowledge, you can't yet do this in your firebase console directly but you can try to execute this in your app. You need to remove this once you have successfully run it. 

```
(async function () {
	const col = await firebase.db.collection('products').get();
	col.forEach((doc) => {
		doc.ref.update({
                        // add new field of your likeness and set default value
			frameSize: {
				eye: 50,
				bridge: 20,
				temple: 142,
				height: 36
			},
			availableColors: ['#000000', '#c500c5', '#840309', '#004d84', '#753600']
		});
	})
})() 
```

Now you all you have to do is to update the products view page to consume these new fields. And on the admin, you need to add a new color input field to control these new field.

**Comment by jgudo** [comment]
Please see the latest commit b15e4db 
Check the changes and additions for this.

**Comment by sourabhz-7** [comment]
Thank you so much sir
