### ISSUE TITLE
Can anyone guide how to create env file and package.json script to run both prod and dev ?

### ISSUE THREAD

**Issue by kingwaleed1** [jgudo/ecommerce-react#29]

**Comment by jgudo** [comment]
The steps to be able to run the dev and prod are included in the ```README``` file. Have you gone through those steps? 
You have to create a ```.env.dev``` and ```.env.prod``` files in the root of your project folder which contains the configuration settings of your firebase project. That means you have to create 2 separate projects in your [Firebase Console](https://console.firebase.google.com/u/0/) and then get the config settings of your project then put them in the env file. 
We need to create a separate firebase project for ```dev``` for testing purposes.

Creating 2 separate firebase projects is optional, you can create just 1 project then use the same config settings for both ```.env.dev``` and ```.env.prod```.  You can use [Firebase Emulators](https://firebase.google.com/docs/rules/emulator-setup) for testing. By running ```firebase emulators:start``` this will run all emulators suite [Functions, Firestore, Authentication, etc.]

The contents of your ```.env.dev``` and ```.env-prod``` looks like this:
```
FIREBASE_API_KEY=AIzaKJgkjhSdfSgkjhdkKJdkjowf
FIREBASE_AUTH_DOMAIN=yourauthdomin.firebaseapp.com
FIREBASE_DB_URL=https://yourdburl.firebaseio.com
FIREBASE_PROJECT_ID=yourproject-id
FIREBASE_STORAGE_BUCKET=yourstoragebucket.appspot.com
FIREBASE_MSG_SENDER_ID=43597918523958
FIREBASE_APP_ID=234598789798798fg3-034
```

If you're wondering where to get the firebase config properties: 
![screenshot](https://user-images.githubusercontent.com/30772059/103249324-9602d200-49a9-11eb-8423-7613eb8da8da.png)

Just click on ```Project Settings``` then scroll to the very bottom to see the config object.

**Comment by jgudo** [comment]
Scripts already included in ```package.json```. No need to create new one.
