### ISSUE TITLE
The node type SpreadProperty has been renamed to SpreadElement at Object.isSpreadProperty

### ISSUE THREAD

**Issue by prashanthrapolu** [jgudo/ecommerce-react#3]
im not able to run project im getting this error when i tried to run using npm run dev-server

**Comment by jgudo** [comment]
Can you provide a screenshot for this error or the whole error message?

**Comment by prashanthrapolu** [comment]
![Capture123](https://user-images.githubusercontent.com/40698768/78097853-108ec900-73fb-11ea-9a4c-b34332140cb0.PNG)

**Comment by jgudo** [comment]
Can you take a screenshot on the part where the error was encountered?

**Comment by prashanthrapolu** [comment]
![7777](https://user-images.githubusercontent.com/40698768/78098497-e211ed80-73fc-11ea-8036-74e9d5708f31.PNG)

**Comment by jgudo** [comment]
Seems like you're missing a babel config file 
Did you just downloaded the repo or cloned it? 

Create a file and name it .babelrc and add the following config

{
    "presets": ["@babel/preset-env", "@babel/preset-react"],
    "plugins": [
      "babel-plugin-transform-class-properties",
      "babel-plugin-transform-object-rest-spread",
      "@babel/plugin-syntax-dynamic-import"
    ]
  }

**Comment by prashanthrapolu** [comment]
yes i added babel config file same issue is getting ,
i had clone the repo and tried to run the code.

**Comment by jgudo** [comment]
Have you referred to same issue here in stackoverflow? [https://stackoverflow.com/questions/53326986/trace-the-node-type-spreadproperty-has-been-renamed-to-spreadelement-at-object](https://stackoverflow.com/questions/53326986/trace-the-node-type-spreadproperty-has-been-renamed-to-spreadelement-at-object)

**Comment by prashanthrapolu** [comment]
yes i had refereed to above stackoverflow but not luck.😣

**Comment by jgudo** [comment]
So I cloned my repo just to check if there were any error and I didn't see any and it's working fine.  
Perhaps you could delete your node_modules and also the package-lock.json and run `npm install` again.

**Comment by prashanthrapolu** [comment]
https://stackoverflow.com/questions/53326986/trace-the-node-type-spreadproperty-has-been-renamed-to-spreadelement-at-object
i have refereed this url and solved the issue.
thank you @jgudo

**Comment by whatneuron** [comment]
Same problem for me,
      "babel-plugin-transform-object-rest-spread",
Changed to 
      "babel-plugin-proposal-object-rest-spread",

in babelrc file... have more issues still but loads of warnings disappeared

**Comment by jgudo** [comment]
@whatneuron  are you running the latest commit? I've updated all the babel plugins. Consider running a git rebase to get the latest. 
```sh
$ git remote add upstream git@github.com:jgudo/ecommerce-react.git
$ git fetch upstream
$ git rebase upstream/master
```
