### ISSUE TITLE
npm run dev-server causes an error

### ISSUE THREAD

**Issue by khizerdev** [jgudo/ecommerce-react#30]
Hey there!

So I have encountered an error when running npm run dev-server. I have made the env file and put my config there to the correct values but for some reason it gives me this error message:

"FirebaseError: projectId must be a string in FirebaseApp.options"

If you know how to fix this issue that will be great.

Thanks,
Khizer

**Comment by jgudo** [comment]
@khizerdev check for typo FIREBASE_PROJECT_ID  . An incorrect projectId wouldn't throw that error. Could be  ```projectId: undefined```  has been set so make sure the env variable FIREBASE_PROJECT_ID exists or no typo included,

**Comment by khizerdev** [comment]
I fix that typo in env variable file but still it says "FirebaseError: projectId must be a string in FirebaseApp.options"

**Comment by jgudo** [comment]
@khizerdev  Could you try copy -pasting the actual projectId property in firebase.js just to check if the env variable is actually not being used? Also, could you try to console.log the value of process.env.FIREBASE_PROJECT_ID if it returns undefined.

**Comment by khizerdev** [comment]
Yes it is returning undefined .

**Comment by jgudo** [comment]
@khizerdev If you named your ```env``` file other than ```.env.dev``` or ```.env.prod``` as I instructed in Readme file, you must configure the ```Dotenv``` in ```webpack/dev.config.js``` or ```webpack/prod.config.js``` to point to your self-named env file.  Maybe that's why causing your problem.
