### ISSUE TITLE
npm Installation 

### ISSUE THREAD

**Issue by JatinThakur2** [jgudo/ecommerce-react#37]
Hello sir, 
I just started react and I saw your project on github and I was trying to run it on my system but when I try to install the npm it saws a lot of error and but there is more I some how managed to install npm but when i try to run the project it give me this error:
ERROR in ./node_modules/normalize.css/normalize.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/group-css-media-queries-loader/lib!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./node_modules/normalize.css/normalize.css)
    Module build failed (from ./node_modules/group-css-media-queries-loader/lib/index.js):
    Error: Cannot find module 'postcss'
could you send me a tutorial video like how to run this project on other system. actually I am just a student and I don't know much about react so it would be so nice if you send me a video.

**Comment by jgudo** [comment]
Hello @JatinThakur2 . It cannot find the module because postcss isn't installed. Make sure to install it. ```npm i -D postcss```

**Comment by JatinThakur2** [comment]
Thank you sir i will try it
