### ISSUE TITLE
Step by step guide to setup locally

### ISSUE THREAD

**Issue by whatneuron** [jgudo/ecommerce-react#4]
Is there any step by step guide to setup locally...

I am even struggling to find out what to get from where and put it into env file, I know it's all firebase related but I am new to firebase

thanks

**Comment by jgudo** [comment]
I've updated the README. Let me know if something else is not clear. 
Basically, after you have created a project in firebase, go to your firebase console and 
in the Your apps card, select the nickname of the app for which you need a config object.
After  that click the *⚙️* gear icon on the side navigation and click `Project Settings`. Scroll to bottom and look for the config object.   
Copy and paste necessary config value into the env file.

**Comment by mehmetusa** [comment]
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

**Comment by mehmetusa** [comment]
Also what do we need to change in package.json in order to run local?

**Comment by jgudo** [comment]
@mehmetusa Can you provide the whole error log?
