### ISSUE TITLE
Blank page.

### ISSUE THREAD

**Issue by Ghost-23** [jgudo/ecommerce-react#43]
Hi.
Firstly - solid work coding the eCommerce site, it looks sick!

I installed the dependencies, did all I should (I believe), and ran the code on my local port but I get a blank screen. VS code says the deployment was successful though.

Did I not do something right?
P.S I'm a noob

**Comment by jgudo** [comment]
Heyyyy. Thanks @Ghost-23! It could be a firebase-related error. Does any error message show up in console?

**Comment by Ghost-23** [comment]
Yes. I've attached 2 images. I don't know what I'm to upgrade if I'm honest.
![Annotation 2021-04-18 004526](https://user-images.githubusercontent.com/55385110/115128678-a7ff9380-9fdf-11eb-944f-0e1a9db8d1b0.png)
![Annotation 2021-04-18 004603](https://user-images.githubusercontent.com/55385110/115128682-a930c080-9fdf-11eb-978c-53e0e20c2318.png)

**Comment by jgudo** [comment]
@Ghost-23 You don't have to worry about that for now. It's the ```uglifyjs-webpack-plugin``` 's dependency issue. 
How about the error log on  your browser that causes blank screen?

**Comment by Ghost-23** [comment]
![Annotation 2021-04-18 011149](https://user-images.githubusercontent.com/55385110/115129091-16922080-9fe3-11eb-907a-f9b2e0fcfd61.png)

**Comment by jgudo** [comment]
Did you create a .env file and named it ```.env.dev``` then putting all necessary configs there?

**Comment by Ghost-23** [comment]
Yeah, I'm a complete noob.

I believe I have. 

![Annotation 2021-04-18 012639](https://user-images.githubusercontent.com/55385110/115129320-2448a580-9fe5-11eb-9bb7-8f8e9a211bab.png)

**Comment by jgudo** [comment]
You can't have any js code on env files. The format should be like this. Just replace the necessary field value.
```
FIREBASE_API_KEY=AIzaKJgkjhSdfSgkjhdkKJdkjowf
FIREBASE_AUTH_DOMAIN=yourauthdomin.firebaseapp.com
FIREBASE_DB_URL=https://yourdburl.firebaseio.com
FIREBASE_PROJECT_ID=yourproject-id
FIREBASE_STORAGE_BUCKET=yourstoragebucket.appspot.com
FIREBASE_MSG_SENDER_ID=43597918523958
FIREBASE_APP_ID=234598789798798fg3-034
```

**Comment by Ghost-23** [comment]
Holy Sh*t that worked!
Thank you so much!

**Comment by jgudo** [comment]
Cheers!
