### ISSUE TITLE
Is it possible to add continuous scroll instead of a button ? thanks

### ISSUE THREAD

**Issue by whatneuron** [jgudo/ecommerce-react#5]
Is it possible to add continuous scroll instead of a button ? 

Button is also fiddly as well, sometimes appears, sometimes doesn't

thanks

**Comment by jgudo** [comment]
You mean an infinite scroll? 
You could make changes to the `watchForScroll` listener in `ProductList` component. Instead of setting `setScrollAtBottom(true);` you can just fire the `onFetchMore()` method. Also remove the button and replace it with a text.
