### ISSUE TITLE
Need to update ReadMe doc

### ISSUE THREAD

**Issue by sachinvrg** [jgudo/ecommerce-react#56]
As you have changed the "firebaseConfig' constants names, so please update README.md file with updated env file variables. 

It should start with "VITE_", like - 
VITE_FIREBASE_API_KEY=AIzaKJgkjhSdfSgkjhdkKJdkjowf
VITE_FIREBASE_AUTH_DOMAIN=yourauthdomin.firebaseapp.com
VITE_FIREBASE_DB_URL=https://yourdburl.firebaseio.com
VITE_FIREBASE_PROJECT_ID=yourproject-id
VITE_FIREBASE_STORAGE_BUCKET=yourstoragebucket.appspot.com
VITE_FIREBASE_MSG_SENDER_ID=43597918523958
VITE_FIREBASE_APP_ID=234598789798798fg3-034

**Comment by jgudo** [comment]
Oh yes I forgot to edit the README file 😅. Thank you
