### ISSUE TITLE
Mobile Field doesn't accept input - onChange

### ISSUE THREAD

**Issue by tarunrajput** [jgudo/ecommerce-react#6]
Hello @jgudo ,

I am unable to input the mobile number on the EditProfile and shipping form.

<ReactPhoneInput
              defaultCountry={'in'}
              disabled={isLoading}
              inputClass={'input-form d-block '}
              inputExtraProps={{ required: true }}
              masks={{ in: '+.. .....-.....' }}
              onChange={onMobileChange}
              placeholder="9876543210"
              value={field.mobile}
          />

**Comment by jgudo** [comment]
Remove or modify the condition in `hooks/useFieldHandler` `line 30` checking for the length of input.

**Comment by jgudo** [comment]
Heya! 
No input showing on the mobile field as you type? 
If you `console.log(e, val)` in `hooks/useFieldHandler` `line30` what values do you get?
 
Can you try to modify or remove the condition in `hooks/useFieldHandler` `line30` , it's actually unnecessary.  You can do validation checking according to the [docs](https://www.npmjs.com/package/react-phone-input-2)
`
<PhoneInput
   isValid={(value, country) => {
    if (value.match(/12345/)) {
      return 'Invalid value: '+value+', '+country.name;
    } else if (value.match(/1234/)) {
      return false;
    } else {
      return true;
    }
  }}
/>
`

Also, setting the initial country option `defaultCountry` replace it with `country` only. 
`<PhoneInput  country={'ph'}  ... />`

**Comment by tarunrajput** [comment]
Hey thanks,
Modifying the `line30  val = e.replace(/[^0-9]+/g,'').slice(data.dialCode.length);` in `hooks/useFieldHandler` worked for me.
